### ISSUE TITLE
Is there a way to view why a test has failed?

### ISSUE THREAD

**Issue by ARichIVC** [ghost-inspector/ghost-inspector-vsts-extension#11]
I can already log in to the ghost portal to view the failure details.  Can I view the same details from within azure devOps?

**Comment by aaronfay** [comment]
Hey @ARichIVC,

Unfortunately we don't provide a way to do this with the extension. You could manually make a couple API calls to [get the suite result ID](https://ghostinspector.com/docs/api/suites/#results) and [then get the test results from that suite result](https://ghostinspector.com/docs/api/suite-results/#results) but that would have to be managed in your build. The test result will have a `passing: false` on the steps that are failing.

**Comment by ARichIVC** [comment]
Thanks @aaronfay , it's not a big deal really, as you say you do get a pass/fail flag as it is.  The ease at which I got the plugin up and running is much more important.  Keep up the great work!

**Comment by aaronfay** [comment]
Thanks for the feedback! 🙏
