### ISSUE TITLE
Optional suite results in xunit format so results can be viewed with other pipeline tests

### ISSUE THREAD

**Issue by mikejonestechno** [ghost-inspector/ghost-inspector-vsts-extension#25]
The current poll function just outputs the results.data.data.passing and shows whether the overall pass result was true or false. 

> Ghost Inspector doesnt output whether it was 1 test or 100 tests that failed!

Add an optional 'xUnit path' parameter that will make a final API call to retrieve the suite results in xUnit format so they can be published and viewed with other pipeline test results.

*The API to retrieve the results in xunit format already exists.*
`${this.suiteResultsBaseUrl}/${suiteResultId}/xunit/?apiKey=`

Add an (optional) final call after getting the suite results to get the xunit report, and save it to a specified path that can be set via task parameter. 

We can then use the built in 'Publish test results' task to publish and view the test results in the pipeline.

task.json
```
  "inputs": [
    {
      "name": "resultPath",
      "type": "string",
      "label": "Result Path",
      "defaultValue": "$(Common.TestResultsDirectory)",
      "required": false,
      "helpMarkDown": "Path to save test suite result report (xUnit v2 format)."
    },
```

index.ts (bottom of file just before return.results)
```
const safeUrl = `${this.suiteResultsBaseUrl}/${suiteResultId}/xunit/?apiKey=`
const resultsUrl = `${safeUrl}${this.request.apiKey}`
console.log('Getting xunit report', `${safeUrl}***`)
const report = await axios.get(resultsUrl)
// additional code to save report to specified path
```

**Comment by aaronfay** [comment]
Hi @mikejonestechno, we've just published [version 1.1.0](https://marketplace.visualstudio.com/items?itemName=ghost-inspector.ghost-inspector-vsts-extension) that should address this for you, thanks for your patience! Would you be willing to give it a test run to make sure it's working as expected?
