### ISSUE TITLE
Problem with custom vars

### ISSUE THREAD

**Issue by olaj** [ghost-inspector/ghost-inspector-vsts-extension#5]
I can't really figure out what is wrong by looking at the code but there seems to be some issue with passing custom variables to this extension.

https://i.imgur.com/1hR7Ya3.png

I have tried like this and also with the startUrl paramater specificed on and only my custom variable. But the custom variable doesn't seem to be posted in the body.

As i said i have tried to figure out what could be wrong with the code but can't really find anything. Am i doing something wrong or is there some bug somewhere.

In the log i see the post and that it doesn't seems to post my custom vars.

If i enter the startUrl:

_POSTing execute request with body https://api.ghostinspector.com/v1/suites/561f6e541b1c48181c620ac7/execute/?apiKey=**** { immediate: 1, startUrl: 'https://beta.alternativeto.net/' }_

If i do not enter the startUrl:

_POSTing execute request with body https://api.ghostinspector.com/v1/suites/561f6e541b1c48181c620ac7/execute/?apiKey=**** { immediate: 1 }_

**Comment by aaronfay** [comment]
Hi @olaj, 

Thanks for reporting this, I've just pushed some changes that will address your issue. When you re-run your build in VSTS, please make sure you are using version `1.0.3` of the plugin (or newer) and you should see the custom JSON parameters passing through the API call to your suite.

<img width="579" alt="screen shot 2018-04-03 at 9 36 16 am" src="https://user-images.githubusercontent.com/1033941/38262894-c0d45082-372b-11e8-9e3e-c2c96d3d1894.png">

Let me know if that is working for you.

**Comment by olaj** [comment]
Seems to work now :)
